### ISSUE TITLE
Basics notebook broken link to notebook `00`

### ISSUE THREAD

**Issue by CBroz1** [datajoint/datajoint-tutorials#40]
The [basics notebook](https://github.com/datajoint/datajoint-tutorials/blob/main/tutorials/01-DataJoint%20Basics.ipynb) has a link to a nonexistent file: `[Connecting to DataBase](00-ConnectingToDatabase.ipynb)`

**Comment by kushalbakshi** [comment]
Thanks, Chris. We've made extensive changes to the introductory tutorial but some of those changes were missed. #41 should've solved it
